using System.Text;
using Dot2Editor.Core.Models;

namespace Dot2Editor.Core.Generation;

/// <summary>
///     Assembles EditorConfig properties into the final .editorconfig text.
///     Sections are emitted "*" first, then alphabetically; properties are sorted
///     by name within a section. Duplicate names within a section: last one wins.
/// </summary>
public static class EditorConfigGenerator
{
    /// <summary>
    ///     Renders properties as the text of a brand-new .editorconfig file.
    ///     To add them to a file that already exists, use <see cref="EditorConfigMerger" /> instead.
    /// </summary>
    /// <param name="properties">The properties to write. Duplicates within a section: last one wins.</param>
    /// <param name="options">Controls the "root = true" line and the header comment.</param>
    /// <returns>The .editorconfig content, using "\n" line endings.</returns>
    public static string Generate(IEnumerable<EditorConfigProperty> properties, ConvertOptions options)
    {
        var sections = new Dictionary<string, Dictionary<string, string>>(StringComparer.Ordinal);
        foreach (var property in properties)
        {
            if (!sections.TryGetValue(property.Section, out var section))
            {
                section = new Dictionary<string, string>(StringComparer.Ordinal);
                sections[property.Section] = section;
            }

            section[property.Name] = property.Value;
        }

        var builder = new StringBuilder();
        if (options.IncludeHeader) builder.Append("# Generated by dot2editor\n");

        if (options.Root) builder.Append("root = true\n");

        foreach (var sectionName in sections.Keys.OrderBy(SectionSortKey).ThenBy(name => name, StringComparer.Ordinal))
        {
            if (builder.Length > 0) builder.Append('\n');

            builder.Append('[').Append(sectionName).Append("]\n");
            foreach (var (name, value) in sections[sectionName].OrderBy(pair => pair.Key, StringComparer.Ordinal))
                builder.Append(name).Append(" = ").Append(value).Append('\n');
        }

        return builder.ToString();
    }

    private static int SectionSortKey(string section)
    {
        return section == "*" ? 0 : 1;
    }
}
