using Dot2Editor.Core.Generation;
using Dot2Editor.Core.Models;

namespace Dot2Editor.Core.Tests.Generation;

public class EditorConfigGeneratorTests
{
    private static readonly ConvertOptions Bare = new() { Root = false, IncludeHeader = false };

    [Fact]
    public void Generate_SortsPropertiesWithinSection()
    {
        var text = EditorConfigGenerator.Generate(new[]
        {
            new EditorConfigProperty("*.cs", "max_line_length", "120"),
            new EditorConfigProperty("*.cs", "indent_size", "4")
        }, Bare);

        Assert.Equal("[*.cs]\nindent_size = 4\nmax_line_length = 120\n", text);
    }

    [Fact]
    public void Generate_StarSectionComesFirst()
    {
        var text = EditorConfigGenerator.Generate(new[]
        {
            new EditorConfigProperty("*.cs", "indent_size", "4"),
            new EditorConfigProperty("*", "insert_final_newline", "true")
        }, Bare);

        Assert.Equal("[*]\ninsert_final_newline = true\n\n[*.cs]\nindent_size = 4\n", text);
    }

    [Fact]
    public void Generate_RootAndHeader()
    {
        var text = EditorConfigGenerator.Generate(
            new[] { new EditorConfigProperty("*.cs", "indent_size", "4") },
            new ConvertOptions());

        Assert.Equal("# Generated by dot2editor\nroot = true\n\n[*.cs]\nindent_size = 4\n", text);
    }

    [Fact]
    public void Generate_DuplicateProperty_LastWins()
    {
        var text = EditorConfigGenerator.Generate(new[]
        {
            new EditorConfigProperty("*.cs", "indent_size", "4"),
            new EditorConfigProperty("*.cs", "indent_size", "2")
        }, Bare);

        Assert.Equal("[*.cs]\nindent_size = 2\n", text);
    }

    [Fact]
    public void Generate_NoProperties_EmitsOnlyPreamble()
    {
        var text = EditorConfigGenerator.Generate(Array.Empty<EditorConfigProperty>(), new ConvertOptions());

        Assert.Equal("# Generated by dot2editor\nroot = true\n", text);
    }
}
