namespace Dot2Editor.Core;

/// <summary>
///     Options controlling the generated .editorconfig.
/// </summary>
public sealed record ConvertOptions
{
    /// <summary>Emit "root = true" at the top of the file.</summary>
    public bool Root { get; init; } = true;

    /// <summary>Emit a "# Generated by dot2editor" header comment.</summary>
    public bool IncludeHeader { get; init; } = true;
}
