using ConsoleAppFramework;
using Dot2Editor.Core;
using Dot2Editor.Core.Generation;
using Dot2Editor.Core.Models;
using Dot2Editor.Core.Parsing;

namespace Dot2Editor.Cli;

internal static class ConvertCommand
{
    /// <summary>
    ///     Converts a JetBrains .DotSettings file (Rider / ReSharper) to .editorconfig.
    /// </summary>
    /// <param name="input">Path to the .DotSettings file, or "-" to read from standard input.</param>
    /// <param name="output">-o, Write the result here. An existing file is merged into, never replaced wholesale.</param>
    /// <param name="overwrite">Replace the output file instead of merging into it.</param>
    /// <param name="noRoot">Omit "root = true" from a newly created file.</param>
    /// <param name="noHeader">Omit the "generated by" header comment from a newly created file.</param>
    /// <param name="showSkipped">List every entry that could not be converted.</param>
    /// <param name="quiet">-q, Do not print the summary.</param>
    public static int Execute(
        [Argument] string input,
        string? output = null,
        bool overwrite = false,
        bool noRoot = false,
        bool noHeader = false,
        bool showSkipped = false,
        bool quiet = false)
    {
        try
        {
            var result = DotSettingsConverter.Convert(
                Read(input),
                new ConvertOptions { Root = !noRoot, IncludeHeader = !noHeader });

            var summary = Write(output, overwrite, result);
            Report(result, summary, showSkipped, quiet);
            return 0;
        }
        catch (Exception e) when (e is CommandFailure or DotSettingsParseException)
        {
            Console.Error.WriteLine($"error: {e.Message}");
            return 1;
        }
    }

    private static string Read(string input)
    {
        try
        {
            return input == "-" ? Console.In.ReadToEnd() : File.ReadAllText(input);
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            throw new CommandFailure($"cannot read {input}: {e.Message}");
        }
    }

    /// <summary>Writes the result and returns the one-line summary describing what happened.</summary>
    private static string Write(string? output, bool overwrite, ConversionResult result)
    {
        if (output is null)
        {
            Console.Out.Write(result.EditorConfigText);
            return $"Converted {Count(result.Properties.Count, "property", "properties")}.";
        }

        try
        {
            // An existing file is merged into so that hand-written settings survive.
            if (!overwrite && File.Exists(output))
            {
                var merged = EditorConfigMerger.Merge(File.ReadAllText(output), result.Properties);
                File.WriteAllText(output, merged.EditorConfigText);
                return $"Merged into {output}: {merged.Added} added, {merged.Updated} updated, " +
                       $"{merged.Unchanged} already up to date.";
            }

            File.WriteAllText(output, result.EditorConfigText);
            return $"Wrote {Count(result.Properties.Count, "property", "properties")} to {output}.";
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            throw new CommandFailure($"cannot write {output}: {e.Message}");
        }
    }

    /// <summary>
    ///     Everything diagnostic goes to stderr, so stdout stays usable as the generated file.
    /// </summary>
    private static void Report(ConversionResult result, string summary, bool showSkipped, bool quiet)
    {
        if (!quiet)
        {
            Console.Error.WriteLine(summary);
            Console.Error.WriteLine($"Skipped {Count(result.Skipped.Count, "entry", "entries")}.");
            if (result.Warnings.Count > 0)
                Console.Error.WriteLine($"{result.Warnings.Count} setting(s) converted only partially.");

            if ((result.Skipped.Count > 0 || result.Warnings.Count > 0) && !showSkipped)
                Console.Error.WriteLine("Run with --show-skipped for the details.");
        }

        if (!showSkipped) return;

        foreach (var warning in result.Warnings)
            Console.Error.WriteLine($"partial: {warning.Key} ({warning.Message})");

        foreach (var skipped in result.Skipped)
            Console.Error.WriteLine($"skipped: {skipped.Key} ({skipped.Reason})");
    }

    private static string Count(int count, string singular, string plural) =>
        $"{count} {(count == 1 ? singular : plural)}";

    /// <summary>An error already phrased for the user; <see cref="Execute" /> turns it into exit code 1.</summary>
    private sealed class CommandFailure(string message) : Exception(message);
}
