namespace Dot2Editor.Core.Tests;

public class DotSettingsConverterTests
{
    [Fact]
    public void Convert_Sample_ProducesExpectedEditorConfig()
    {
        var result = DotSettingsConverter.Convert(TestDataFiles.Sample);

        const string expected =
            "# Generated by dot2editor\n" +
            "root = true\n" +
            "\n" +
            "[*.cs]\n" +
            "csharp_style_var_for_built_in_types = false\n" +
            "dotnet_naming_rule.parameters.severity = warning\n" +
            "dotnet_naming_rule.parameters.style = parameters_style\n" +
            "dotnet_naming_rule.parameters.symbols = parameters_symbols\n" +
            "dotnet_naming_style.parameters_style.capitalization = camel_case\n" +
            "dotnet_naming_symbols.parameters_symbols.applicable_accessibilities = *\n" +
            "dotnet_naming_symbols.parameters_symbols.applicable_kinds = parameter\n" +
            "dotnet_style_predefined_type_for_locals_parameters_members = true\n" +
            "indent_size = 4\n" +
            "max_line_length = 120\n" +
            "resharper_csharp_align_linq_query = true\n" +
            "resharper_csharp_anonymous_method_declaration_braces = next_line\n";

        Assert.Equal(expected, result.EditorConfigText);
        Assert.Equal(12, result.Properties.Count);
    }

    [Fact]
    public void Convert_Sample_ReportsSkippedEntries()
    {
        var result = DotSettingsConverter.Convert(TestDataFiles.Sample);

        var skipped = Assert.Single(result.Skipped);
        Assert.Contains("SettingsMigration", skipped.Key);
    }

    [Fact]
    public void Convert_Sample_HasNothingToWarnAbout()
    {
        var result = DotSettingsConverter.Convert(TestDataFiles.Sample);

        Assert.Empty(result.Warnings);
    }

    [Fact]
    public void Convert_RespectsOptions()
    {
        var result = DotSettingsConverter.Convert(
            TestDataFiles.Sample,
            new ConvertOptions { Root = false, IncludeHeader = false });

        Assert.StartsWith("[*.cs]\n", result.EditorConfigText);
    }
}
