using Dot2Editor.Core.Models;

namespace Dot2Editor.Core.Tests;

/// <summary>
///     EdgeCases.DotSettings contains only entries that cannot be converted, so the
///     whole file must come back as skipped — with a reason each — and never throw.
/// </summary>
public class EdgeCaseConversionTests
{
    private static readonly ConversionResult Result = DotSettingsConverter.Convert(TestDataFiles.EdgeCases);

    [Fact]
    public void NothingIsConverted()
    {
        Assert.Empty(Result.Properties);
    }

    [Fact]
    public void EveryEntryIsReportedWithAReason()
    {
        Assert.NotEmpty(Result.Skipped);
        Assert.All(Result.Skipped, s => Assert.False(string.IsNullOrWhiteSpace(s.Reason)));
    }

    [Fact]
    public void OutputIsStillAValidPreamble()
    {
        Assert.Equal("# Generated by dot2editor\nroot = true\n", Result.EditorConfigText);
    }

    [Fact]
    public void ElementsWithoutAKeyAreIgnoredEntirely()
    {
        // The file has one <s:String> with no x:Key; it must not surface as skipped.
        Assert.DoesNotContain(Result.Skipped, s => string.IsNullOrEmpty(s.Key));
    }
}
